import React, { useState, useEffect } from 'react';
import { apiFetch } from '../api';

export default function Analytics({ token }) {
  const [stats, setStats] = useState({
    conversationsCount: 0,
    aiContainmentRate: 100,
    hoursSaved: 0,
    revenueInfluenced: 0,
    ordersStarted: 0,
    ordersCompleted: 0,
    averageLatency: "N/A",
    humanTakeovers: 0,
    
    // AI Quality Metrics (N/A since not tracked in DB)
    intentAccuracy: "N/A",
    groundingRate: "N/A",
    hallucinationRate: "N/A",
    recommendationQuality: "N/A",

    topProducts: []
  });

  useEffect(() => {
    fetchStats();
  }, []);

  const fetchStats = async () => {
    try {
      const res = await apiFetch('/api/analytics/dashboard');
      if (res.ok) {
        const data = await res.json();
        setStats(prev => ({
          ...prev,
          conversationsCount: data.total_conversations,
          aiContainmentRate: Math.round(data.ai_containment_rate),
          humanTakeovers: data.human_takeover_count,
          hoursSaved: parseFloat(((data.total_conversations * 15) / 60).toFixed(1)), // Assumes avg 15 mins saved per conversation instead of 2 mins
          revenueInfluenced: data.revenue_influenced,
          ordersStarted: data.orders_started,
          ordersCompleted: data.orders_completed,
          topProducts: data.top_products || []
        }));
      }
    } catch (err) {
      console.error("Error fetching stats:", err);
    }
  };

  return (
    <div style={styles.container}>
      {/* SECTION 1: BUSINESS PERFORMANCE */}
      <div style={styles.sectionHeader}>
        <h2>📈 Business Performance</h2>
        <p style={styles.subtitle}>Direct monetary value and efficiency gains generated by the AI sales assistant.</p>
      </div>
      <div style={styles.metricsGrid}>
        <div className="glass-card animate-fade-in" style={styles.metricCard}>
          <div style={styles.metricLabel}>Revenue Influenced</div>
          <div style={{ ...styles.metricValue, color: 'var(--accent-secondary)' }}>
            ₹{stats.revenueInfluenced.toLocaleString('en-IN')}
          </div>
          <div style={styles.metricChange}>💰 Influenced by AI recommendations</div>
        </div>

        <div className="glass-card animate-fade-in" style={{ ...styles.metricCard, animationDelay: '0.1s' }}>
          <div style={styles.metricLabel}>Order Conversions</div>
          <div style={styles.metricValue}>
            {stats.ordersCompleted} / {stats.ordersStarted}
          </div>
          <div style={styles.metricChange}>🎯 Completed vs. started checkouts</div>
        </div>

        <div className="glass-card animate-fade-in" style={{ ...styles.metricCard, animationDelay: '0.2s' }}>
          <div style={styles.metricLabel}>Estimated Hours Saved</div>
          <div style={{ ...styles.metricValue, color: 'var(--success)' }}>
            {stats.hoursSaved}h
          </div>
          <div style={styles.metricChange}>⏳ Equivalent time savings for staff</div>
        </div>
      </div>

      {/* SECTION 2: OPERATIONAL HEALTH */}
      <div style={{ ...styles.sectionHeader, marginTop: '1rem' }}>
        <h2>⚡ Operational Health</h2>
        <p style={styles.subtitle}>Audit response latency, containment rates, and human escalations.</p>
      </div>
      <div style={styles.metricsGrid}>
        <div className="glass-card animate-fade-in" style={styles.metricCard}>
          <div style={styles.metricLabel}>AI Containment Rate</div>
          <div style={{ ...styles.metricValue, color: 'var(--accent-secondary)' }}>
            {stats.aiContainmentRate}%
          </div>
          <div style={styles.metricChange}>🤖 Chats contained entirely by AI</div>
        </div>

        <div className="glass-card animate-fade-in" style={{ ...styles.metricCard, animationDelay: '0.1s' }}>
          <div style={styles.metricLabel}>Human Takeovers</div>
          <div style={{ ...styles.metricValue, color: 'var(--accent-primary)' }}>
            {stats.humanTakeovers}
          </div>
          <div style={styles.metricChange}>👥 Handed off to store staff</div>
        </div>

        <div className="glass-card animate-fade-in" style={{ ...styles.metricCard, animationDelay: '0.2s' }}>
          <div style={styles.metricLabel}>Average Latency</div>
          <div style={styles.metricValue}>
            {stats.averageLatency !== "N/A" ? `${stats.averageLatency}s` : "N/A"}
          </div>
          <div style={styles.metricChange}>⏱ Latency tracking not configured</div>
        </div>
      </div>

      {/* SECTION 3: AI QUALITY METRICS */}
      <div style={{ ...styles.sectionHeader, marginTop: '1rem' }}>
        <h2>🎯 AI NLU & Recommendation Quality</h2>
        <p style={styles.subtitle}>Diagnostic metrics indicating classification precision, grounding confidence, and hallucination safety.</p>
      </div>
      <div style={styles.metricsGrid}>
        <div className="glass-card animate-fade-in" style={styles.metricCard}>
          <div style={styles.metricLabel}>Intent Classification</div>
          <div style={{ ...styles.metricValue, color: 'var(--text-muted)' }}>
            {stats.intentAccuracy !== "N/A" ? `${stats.intentAccuracy}%` : "N/A"}
          </div>
          <div style={styles.metricChange}>🔍 Data pending model metrics telemetry</div>
        </div>

        <div className="glass-card animate-fade-in" style={{ ...styles.metricCard, animationDelay: '0.1s' }}>
          <div style={styles.metricLabel}>Grounding Rate</div>
          <div style={{ ...styles.metricValue, color: 'var(--text-muted)' }}>
            {stats.groundingRate !== "N/A" ? `${stats.groundingRate}%` : "N/A"}
          </div>
          <div style={styles.metricChange}>📖 Data pending validation logging</div>
        </div>

        <div className="glass-card animate-fade-in" style={{ ...styles.metricCard, animationDelay: '0.2s' }}>
          <div style={styles.metricLabel}>Hallucination Rate</div>
          <div style={{ ...styles.metricValue, color: 'var(--text-muted)' }}>
            {stats.hallucinationRate !== "N/A" ? `${stats.hallucinationRate}%` : "N/A"}
          </div>
          <div style={styles.metricChange}>⚠️ Data pending guardrail logs</div>
        </div>
      </div>

      {/* Conversion details list */}
      <div style={styles.detailsSection}>
        <div className="glass-panel" style={styles.detailCard}>
          <h3>🔥 Top Recommendations</h3>
          <p style={styles.subtitle}>Most popular items matched by AI and recommended to customers.</p>
          <div style={styles.productsList}>
            {stats.topProducts.map((p, idx) => (
              <div key={p.sku} style={styles.productRow}>
                <div style={styles.prodRank}>#{idx + 1}</div>
                <div style={styles.prodInfo}>
                  <strong>{p.name}</strong>
                  <small style={{ color: 'var(--text-secondary)' }}>SKU: {p.sku}</small>
                </div>
                <div style={styles.prodViews}>{p.views} recommendations</div>
              </div>
            ))}
          </div>
        </div>

        <div className="glass-panel" style={styles.detailCard}>
          <h3>📊 Order Funnel Statistics</h3>
          <p style={styles.subtitle}>Funnel conversion stages for customer purchasing.</p>
          <div style={styles.funnel}>
            <div style={styles.funnelItem}>
              <span>1. Total Inbound Customer Conversations (100%)</span>
              <div style={styles.barContainer}>
                <div style={{ ...styles.bar, width: '100%', background: 'rgba(255, 255, 255, 0.1)' }} />
                <span>{stats.conversationsCount} chats</span>
              </div>
            </div>
            <div style={styles.funnelItem}>
              <span>2. Checkout / Order Initiated ({stats.conversationsCount > 0 ? Math.round((stats.ordersStarted / stats.conversationsCount) * 100) : 0}%)</span>
              <div style={styles.barContainer}>
                <div style={{ ...styles.bar, width: `${stats.conversationsCount > 0 ? Math.min(100, Math.round((stats.ordersStarted / stats.conversationsCount) * 100)) : 0}%`, background: 'var(--accent-primary)' }} />
                <span>{stats.ordersStarted} carts</span>
              </div>
            </div>
            <div style={styles.funnelItem}>
              <span>3. Paid & Completed Orders ({stats.conversationsCount > 0 ? Math.round((stats.ordersCompleted / stats.conversationsCount) * 100) : 0}%)</span>
              <div style={styles.barContainer}>
                <div style={{ ...styles.bar, width: `${stats.conversationsCount > 0 ? Math.min(100, Math.round((stats.ordersCompleted / stats.conversationsCount) * 100)) : 0}%`, background: 'var(--success)' }} />
                <span>{stats.ordersCompleted} orders</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

const styles = {
  container: {
    padding: '0 1rem 2rem 1rem',
    overflowY: 'auto',
    height: 'calc(100vh - 90px)',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '1rem',
  },
  metricCard: {
    borderRadius: 'var(--border-radius-md)',
  },
  metricLabel: {
    fontSize: '0.8rem',
    fontWeight: '700',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  metricValue: {
    fontSize: '2.5rem',
    fontFamily: 'var(--font-title)',
    fontWeight: '800',
    margin: '0.5rem 0',
  },
  metricChange: {
    fontSize: '0.8rem',
    color: 'var(--text-muted)',
  },
  detailsSection: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  detailCard: {
    padding: '1.5rem',
    borderRadius: 'var(--border-radius-md)',
  },
  subtitle: {
    fontSize: '0.8rem',
    color: 'var(--text-secondary)',
    marginBottom: '1rem',
  },
  productsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  productRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.75rem',
    background: 'rgba(255, 255, 255, 0.02)',
    borderRadius: 'var(--border-radius-sm)',
    border: '1px solid var(--glass-border)',
  },
  prodRank: {
    fontSize: '1rem',
    fontFamily: 'var(--font-title)',
    fontWeight: '800',
    color: 'var(--accent-secondary)',
    width: '40px',
  },
  prodInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  prodViews: {
    fontSize: '0.85rem',
    fontWeight: '600',
    color: 'var(--accent-primary)',
  },
  funnel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  funnelItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
    fontSize: '0.85rem',
  },
  barContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  bar: {
    height: '10px',
    borderRadius: '5px',
  },
  sectionHeader: {
    borderBottom: '1px solid var(--glass-border)',
    paddingBottom: '0.5rem',
    marginBottom: '0.5rem',
  },
};
