import pytest
from unittest.mock import patch, MagicMock
from tests.conftest import app, TestingSessionLocal, clean_tables
from app import models
from app.routers.webhooks import process_message_async

@pytest.fixture(autouse=True)
def setup_teardown():
    db = TestingSessionLocal()
    clean_tables(db)
    db.close()
    yield

def test_visual_search_thresholds():
    db = TestingSessionLocal()

    # 1. Create dummy Organization, User, Conversation
    org = models.Organization(name="Pushpalatha Silks", whatsapp_number="+919900001111")
    db.add(org)
    db.commit()
    db.refresh(org)

    conv = models.Conversation(organization_id=org.id, customer_phone="+919999999999", customer_name="Sita Reddy")
    db.add(conv)
    db.commit()
    db.refresh(conv)

    # Mock classify_intent to return 'product_visual_search'
    # Mock extract_entities to return a category 'Silk' and budget_max=3000
    mock_entities = {
        "product_type": "Silk",
        "color": None,
        "fabric": "Silk",
        "size": None,
        "budget_min": None,
        "budget_max": 3000.0,
        "gender": None
    }

    # Case A: 0 matches, but we have a product costing 3500 in catalog
    p_expensive = models.Product(
        organization_id=org.id,
        sku="SKU-EXP",
        name="Expensive Silk Saree",
        price=3500.0,
        color="Red",
        fabric="Silk",
        stock_count=5,
        image_urls=["https://example.com/expensive.jpg"],
        embedding_status="completed"
    )
    db.add(p_expensive)
    db.commit()

    with patch("app.ai_service.classify_intent", return_value="product_visual_search"), \
         patch("app.ai_service.extract_entities", return_value=mock_entities), \
         patch("app.bsp_service.send_whatsapp_message") as mock_send:
        
        process_message_async(str(org.id), str(conv.id), "show me silk sarees under 3000")
        
        # Verify 0-match text response offers starting price band of ₹3500
        sent_messages = db.query(models.Message).filter(models.Message.conversation_id == conv.id).all()
        # Find the text message generated by the AI
        ai_msgs = [m for m in sent_messages if m.sender == "ai"]
        assert len(ai_msgs) >= 1
        assert "starting from ₹3500" in ai_msgs[0].content

    # Clean up and setup Case B: 1-6 matches
    clean_tables(db)
    # Re-insert org & conv
    org = models.Organization(name="Pushpalatha Silks", whatsapp_number="+919900001111")
    db.add(org)
    db.commit()
    conv = models.Conversation(organization_id=org.id, customer_phone="+919999999999", customer_name="Sita Reddy")
    db.add(conv)
    db.commit()

    # Create 3 matching products (between 1 and 6 matches)
    for i in range(3):
        p = models.Product(
            organization_id=org.id,
            sku=f"SKU-{i}",
            name=f"Silk Saree {i}",
            price=2500.0,
            color="Red",
            fabric="Silk",
            stock_count=5,
            image_urls=[f"https://example.com/saree{i}.jpg"],
            embedding_status="completed"
        )
        db.add(p)
    db.commit()

    with patch("app.ai_service.classify_intent", return_value="product_visual_search"), \
         patch("app.ai_service.extract_entities", return_value=mock_entities), \
         patch("app.bsp_service.send_whatsapp_message") as mock_send:
        
        process_message_async(str(org.id), str(conv.id), "show me silk sarees under 3000")
        
        # Verify 3 individual image messages are created
        sent_messages = db.query(models.Message).filter(models.Message.conversation_id == conv.id).all()
        ai_image_msgs = [m for m in sent_messages if m.sender == "ai" and m.message_type == "image"]
        assert len(ai_image_msgs) == 3
        assert ai_image_msgs[0].content == "Silk Saree 0 — ₹2500"

    # Clean up and setup Case C: 7+ matches
    clean_tables(db)
    # Re-insert org & conv
    org = models.Organization(name="Pushpalatha Silks", whatsapp_number="+919900001111")
    db.add(org)
    db.commit()
    conv = models.Conversation(organization_id=org.id, customer_phone="+919999999999", customer_name="Sita Reddy")
    db.add(conv)
    db.commit()

    # Create 8 matching products
    for i in range(8):
        p = models.Product(
            organization_id=org.id,
            sku=f"SKU-{i}",
            name=f"Silk Saree {i}",
            price=2500.0,
            color="Red",
            fabric="Silk",
            stock_count=5,
            image_urls=[f"https://example.com/saree{i}.jpg"],
            embedding_status="completed"
        )
        db.add(p)
    db.commit()

    with patch("app.ai_service.classify_intent", return_value="product_visual_search"), \
         patch("app.ai_service.extract_entities", return_value=mock_entities), \
         patch("app.bsp_service.send_whatsapp_message") as mock_send:
        
        process_message_async(str(org.id), str(conv.id), "show me silk sarees under 3000")
        
        # Verify 4 image messages + 1 gallery link message are created
        sent_messages = db.query(models.Message).filter(models.Message.conversation_id == conv.id).all()
        ai_image_msgs = [m for m in sent_messages if m.sender == "ai" and m.message_type == "image"]
        ai_text_msgs = [m for m in sent_messages if m.sender == "ai" and m.message_type == "text"]
        
        assert len(ai_image_msgs) == 4
        assert len(ai_text_msgs) == 1
        assert "browse the full collection here" in ai_text_msgs[0].content
        assert "pushpalatha-silks" in ai_text_msgs[0].content

    db.close()
