"""Add Notification table and update Decision Engine schemas

Revision ID: b2fbe48c9249
Revises: 
Create Date: 2026-07-08 12:22:07.426712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2fbe48c9249'
down_revision: Union[str, None] = 'a0000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('approval_request_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('approval_requests', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('approval_requests', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('approval_requests', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    op.add_column('approval_requests', sa.Column('retrieval_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('approval_requests', sa.Column('grounding_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('approval_requests', sa.Column('decision_engine_version', sa.String(length=50), nullable=True))
    op.add_column('approval_requests', sa.Column('rule_triggered', sa.String(length=100), nullable=True))
    op.drop_column('approval_requests', 'risk_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('approval_requests', 'rule_triggered')
    op.drop_column('approval_requests', 'decision_engine_version')
    op.drop_column('approval_requests', 'grounding_score')
    op.drop_column('approval_requests', 'retrieval_ids')
    op.drop_column('approval_requests', 'prompt_version')
    op.drop_column('approval_requests', 'llm_model')
    op.drop_column('approval_requests', 'risk_score')
    op.drop_table('notifications')
    # ### end Alembic commands ###
