"""add_image_embedding

Revision ID: bcf53b84a362
Revises: f6fce6b78e4f
Create Date: 2026-08-02 14:03:44.919463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bcf53b84a362'
down_revision: Union[str, None] = 'f6fce6b78e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True))
    op.add_column('products', sa.Column('image_embedding_status', sa.String(length=50), server_default='pending', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_embedding_status')
    op.drop_column('products', 'image_embedding')
    # ### end Alembic commands ###
